{% set name = "ddt" %}
{% set version = "1.1.3" %}
{% set sha256 = "313bb000f0cf8175bee0ac31cf944aaf5e0041dc202a55fe6f049fe078764690" %}
{% set repo = "txels" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ repo }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python

test:
  requires:
    - flake8
    - nose
    - six >=1.4.0
    - pyyaml
    - mock
    - pytest
  source_files:
    - test/*
  commands:
    - py.test

about:
  home: https://github.com/txels/ddt
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'DDT (Data-Driven Tests) allows you to multiply one test case by
   running it with different test data, and make it appear as multiple test
   cases.'
  description: 'DDT (Data-Driven Tests) allows you to multiply one test case by
   running it with different test data, and make it appear as multiple test
   cases.'
  doc_url: http://ddt.readthedocs.io/en/latest/
  dev_url: https://github.com/txels/ddt

extra:
  recipe-maintainers:
    - CJ-Wright
