travis:
  secure:
    BINSTAR_TOKEN: rKvKW23JK6EzAyinefGyEes3MyznQ0o6hvWtCeGqjgBLLjA2Sk+6ytsYc6gwY1H3L9xYmv2QpDyYtT+DKactcu7Jwc22mRvD83dJnxRPgDGTC+KU36bQytqNWBIttnSiOzJQXJEBFL9l4oiF9OzTSt3gTDnNp2Km78bhrKguYWmG20H9wl5WeQLS+SsFfwFAu6i5ZqXqV5XMi8PTt9GcBxfejYxvNOgbABYMeQVD9HgfVlo13qAoglMTqiCjHsoMngH/K1dgBbZDLYYT3PvQ9Bv2QDggbq6jQUFb09Wlu1D/0UDfhs5G5VB+pRybis9Yn6wgaqjUWZy1KWPz0czaYlk3ZgnPxqdRQHM0zWFy2WT/9zv21e9hX4T+Ebx90TwtNmOzj5bxtEUTPXPVAinfv05UvYiDlOhnO89hxKCcohWcm2vbIxs6cSK4DPXO9TRtZz1azQ2LLkhthxZE3VdOsquT36wbUcylwfUtMSTRJ3D0zxUfZES9Vh1gZ0AAV+dGZCKIVdmI2LFAW+lInwcHwx6rnbVdXlsI8MNK0ZNMP5LRpvzC6piGU6EsDtNUr/e3pqfaY7S2FzhdfJpC5NaWSQM4rsAirQXKPUBqVwHirT2sw90rywh1N8HnKjWhLO/IDTOZ/SGvjd0oTZgwH6bSOGakwROeU92TvLKedbPB9Uo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
