travis:
  secure:
    BINSTAR_TOKEN: wJeaT3WYNR3tCNilLI0Mc/GvCE9jm7XX10LmD+KXatEr7EPH2BT8I+p0paj262K+coIDWa39LDspoinS3Sc4Ux+qQtR7BMJmwgBrlkkS4Mj6O5b3qaumMsPmu1DsN3JHfbeTjcCTDMKHgmPHuQbM/ZhH8NBofynjeQqe4AIUihf9fPRI+sJsWPyrEmy1YXaK0VAuPvMGtm5A2IjdZ3nXTxLqun2tVV46KyE8rVCBw/XBJYiUTGOmjICx+IlgtcH0+W/pwJOVfuAFBtxT3dDfPbTuFvwgS0EGzeBZt8SaYOy3ZbTOovCiBja40ETg688H1I37rg1rfqZarTuQ/PuLbB/UyPoYQGGsHeL3uBkOr5WlxCc6N5ciWNAfUFZMHO/YDfbIY19jofUS4XpuKMfR+Sm6D1rEMzNgaMIE3qBmfGscM/+7dlpXudYZXB+m078diAxnDAQmnurKrNGWkIkqe1j+QpO5NKEhzf724DuMtgSnPE+np+6jtORn/SlqgLYZnKUFuF3JJvT2XNYPKZKZlXDN/EgTqaKW8xtwEGFG9pJu+vQqF6uiOkQbswbuqloYpT88beNqub3UYaXH0dn1xJYKkv8HPplPBq3Mh7Msi+ZA+0t91lW0wONoDlmuqvAsnD1HSv59ZTct9Hw4qbhCQWPozjk82sE7u3dllf9p8LM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
conda_forge_output_validation: true
