travis:
  secure:
    BINSTAR_TOKEN: ERv4wG7h3Aqjsx37mCzyMzDE5WAchTeFY0ei3FsXAhF9NOmV4N80xnu9qN68YJ6Qw1DwyAgZu9rRqsDdDic5HtCje5NmPUi8ZMz8FUAlKKA1m4punRGj+bymUy9cAQFvWfSkfeQ3+H45vNUmTZ78yuQKZ4qUrJ8IEsOFSo15jXS+KC3423tYYD22geMJCcIpZH1WgKOIEh7+RtLS7aszv5zvx+1PAOzj2dIYFqMuNk+qZiG0CrXhCdL6/vh7cWqWVXZezpidM1tabzq2mVt/GNFHCy8C3msD32zewZj96/JVXpm/pX4v8RbSow1i4Re7bJdDizw2UaNMx8sU1zYcQOHgj+CNDY974gkb9cE8bpTnm59YTVEDmL/6JgYoPb7quZODPWYMKvd3CW/2neHVUZlhhpYhxSx58GwTnejriYlbBFvW02JWJU1OdYJT1ZIY4w3X2u2uDOxaGrkXNel29SRQdSJvdZE/3LAAO7C8wfUS7HR6y/jJ/5Kypg1GM/rzsL6IrhfasIbaAuvOxBIvBEtPOyj508R03YdGILBQ8wAEtk/0Qryb2JnbAQcvX0h687Qbde06oEAE4sgWajgWBV0J8tEMS6vxYWK6bDn9tEmWiHnZXnnfAYqtcoP2vW1OAsG18aHYY6hOYdAv+w6j0H0k5nwBtJA1zyjLB/u8GKs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
